upload_max_filesize = 10M
post_max_size = 10M
memory_limit = 512M
max_execution_time = 300
; log de errores para Docker
error_reporting = E_ALL
display_errors = Off
log_errors = On
error_log = /dev/stderr