version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventario_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - inventario_network

  mysql:
    image: mysql:8.0
    container_name: inventario_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventario
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inventario_network

  composer:

volumes:
  db_data:

networks:
  inventario_network:
