name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.4
        tools: composer:v2
        coverage: xdebug
    - name: Create Database
      run: touch ./database/database.sqlite
    - name: Copy .env
      run: cp .env.testing .env
    - name: Install Dependencies
      run: composer install -q --optimize-autoloader --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Run migrations
      run: php artisan migrate
    - name: Execute tests via PHPUnit/Pest
      run: php artisan test --env=testing
