name: Tests
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'routes/**'
      - 'tests/**'
      - 'composer.*'
      - 'phpunit.xml'
      - '.env.example'

jobs:
  ci:
    name: Execute Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      # - name: Setup Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '22'
      #     cache: 'pnpm'

      # - name: Setup pnpm
        # uses: pnpm/action-setup@v4
        # with:
          # version: 8
          # standalone: true

      # - name: Install pnpm manually
      #   run: npm install -g pnpm

      # - name: Install Node Dependencies
      #   run: pnpm install --frozen-lockfile

      # - name: Build Assets
      #   run: pnpm run build

      - name: Install PHP Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Tests
        run: ./vendor/bin/phpunit
